### ISSUE TITLE
Support for scifunc_block_m block

### ISSUE THREAD

**Issue by diptighosalkar** [FOSSEE/xcos_on_cloud#232]
According to new modified code in python and Js , following modification need to be done in scifunc_block_m :

~~Flow of adding sci file need to be fixed.~~
Import parameter need to be fixed for block.
Opening of multiple parameters need to be fixed according to flow.

**Comment by sunilshetye** [comment]
sci file flow has been merged with uploading script. Check #235, #236, #237

**Comment by diptighosalkar** [comment]
PR #256  fix following things :
Import parameter  for block.
Opening of multiple parameters according to flow.
