### ISSUE TITLE
js: inverse(): For variables: get the values for variable from workspace/context and then parse. 

### ISSUE THREAD

**Issue by sunilshetye** [FOSSEE/xcos_on_cloud#307]
**Is your feature request related to a problem? Please describe.**
 Blocks with variables as parameter value are not loaded properly.

**Describe the solution you'd like**
Some javascript functions take a matrix as input. They fail when a variable is passed to them. Make them support variables also. This is for functions which convert value in matrix format and also used in getting port numbers of block e.g. **inverse() and Matrixinverse()**

Make them support variables by getting value stored in those workspace/context variables by accessing context and workspace by creating new function to access them.

Merged inverse and Matrixinverse functionality so that one function and handle both inputs like Inverse ->  [1,1,1,1]      and   MatrixInverse -> [1,1;1,1] 

Proper formatted value can be obtained from inverse() which can be used to pass to function like size(), setio() for creating port of block while importing block diagram.

**Comment by diptighosalkar** [comment]
Issue is closed in PR #312
