### ISSUE TITLE
js: size(): For variables: get the size and type from the variables saved in browser

### ISSUE THREAD

**Issue by sunilshetye** [FOSSEE/xcos_on_cloud#308]
**Is your feature request related to a problem? Please describe.**
 Blocks with variables as parameter was are not loaded properly and also was not giving proper size of value.

**Describe the solution you'd like**
If variable is used as parameter in any block, then value of that variable should be retrieve from variable(workspace variable /context variable) and then convert to proper matrix format and then only pass to function size() so that proper size could be get for further use. 
If variable doesn't exist or doesn't have proper value it should be handled and message should be given to user.

**Comment by diptighosalkar** [comment]
Issue is closed in PR #312
