### ISSUE TITLE
Parameter and Label not getting updated in MAXMIN block

### ISSUE THREAD

**Issue by diptighosalkar** [FOSSEE/xcos_on_cloud#321]
**Describe the bug**
When user change parameter value for Min(1) or Max(2) input,  label on block as well as value is not getting updated.

**To Reproduce**
1. Drag MAXMIN block on canvas on xcos on cloud.
2. Click on block , open parameter window and change value from 2 to 1 for  Min(1) or Max(2) input.

**Expected behavior**
Label should change to Min if you enter 1 as value and Max if you enter 2 as value and even value should get update in parameter window.

**Additional context**
Functioning of this block can be checked in scilab desktop to get a clear picture about expected behaviour.

**Comment by sunilshetye** [comment]
Closed by #329
